
Public Class frmIDFormat
    Private Sub llblLogsDef_LinkClicked(ByVal sender As System.Object, ByVal e As System.Windows.Forms.LinkLabelLinkClickedEventArgs) Handles llblLog.LinkClicked
        txtLogs.Text = "CAMPUSL"
    End Sub

    Private Sub llblMonitDef_LinkClicked(ByVal sender As System.Object, ByVal e As System.Windows.Forms.LinkLabelLinkClickedEventArgs) Handles llblMonitoring.LinkClicked
        txtMonitoring.Text = "CAMPUSM"
    End Sub

 
    Private Sub btnSave_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnSave.Click
        lDef.Text = "SYSTEM ID FORMAT CHANGER"
        If MB("Do you want to save this changes?", "?") = "n" Then Return
        UPDATEr("tbleid", "format='" & txtLogs.Text.Trim.ToUpper & "'", "field like '%Logs%'")
        UPDATEr("tbleid", "format='" & txtMonitoring.Text.Trim.ToUpper & "'", "field like '%MonitoringLogs%'")
        UPDATEr("tbleid", "format='" & txtPassCode.Text.Trim.ToUpper & "'", "field like '%Passcode%'")
        UPDATEr("tbleid", "format='" & txtAnn.Text.Trim.ToUpper & "'", "field like '%AnnouncementID%'")
        UPDATEr("tbleid", "value=1", "field='IDFormat'")
        LOGS("Successfully change ID prefix for records.")
        MB("Saved!") : Me.Close()
    End Sub

    Private Sub txtLogs_GotFocus(ByVal sender As Object, ByVal e As System.EventArgs) Handles txtLogs.GotFocus
        lDef.Text = "SYSTEM TRACKS OR USER ACTIVITIES HISTORY RECORDS"
        txtLogs_TextChanged(sender, e)
    End Sub

    Private Sub txtLogs_TextChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles txtLogs.TextChanged
        lblPrev.Text = txtLogs.Text.Trim & "-00000"

    End Sub

    Private Sub txtMonitoring_GotFocus(ByVal sender As Object, ByVal e As System.EventArgs) Handles txtMonitoring.GotFocus
        lDef.Text = "STUDENT LOGS RECORDS"
        txtMonitoring_TextChanged(sender, e)
    End Sub

    Private Sub txtMonitoring_TextChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles txtMonitoring.TextChanged
        lblPrev.Text = txtMonitoring.Text.Trim & "-00000"
    End Sub

    Private Sub txtPassCode_GotFocus(ByVal sender As Object, ByVal e As System.EventArgs) Handles txtPassCode.GotFocus
        lDef.Text = "STUDENT PASSCODE: AUTOGENERATED PASSCODE, the security for alternative log for student"
        txtPassCode_TextChanged(sender, e)
    End Sub

    Private Sub txtPassCode_TextChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles txtPassCode.TextChanged
        lblPrev.Text = txtPassCode.Text.Trim & "-00000"
    End Sub

    Private Sub txtAnn_GotFocus(ByVal sender As Object, ByVal e As System.EventArgs) Handles txtAnn.GotFocus
        lDef.Text = "CAMPUS ANNOUNCEMENT RECORDS"
        txtAnn_TextChanged(sender, e)
    End Sub

    Private Sub txtAnn_TextChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles txtAnn.TextChanged
        lblPrev.Text = txtAnn.Text.Trim & "-00000"
    End Sub

    Private Sub frmIDFormat_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        If Not CBool(gIDVal("IDFormat")) Then MB("System ID Format Changer" & vbCr & vbCr & "It lets you to set the prefix of the future records ID")
    End Sub

    Private Sub llblPass_LinkClicked(ByVal sender As System.Object, ByVal e As System.Windows.Forms.LinkLabelLinkClickedEventArgs) Handles llblPass.LinkClicked
        txtPassCode.Text = "PUP"
    End Sub

    Private Sub llblAnn_LinkClicked(ByVal sender As System.Object, ByVal e As System.Windows.Forms.LinkLabelLinkClickedEventArgs) Handles llblAnn.LinkClicked
        txtAnn.Text = "CAMPUSA"
    End Sub
End Class